#!/bin/bash

PORT=80

while read line; do
    regex="[[:space:]]*#[^\n]*";
    line=${line%%$regex}; # strip trailing whitespace and comments
    regex="=[^\n]*";
    if [ "${line%%$regex}" == "PORT" ]; then
        PORT=${line:5};
        break;
    fi
done < options

echo "Running server on port $PORT";

socat TCP4-LISTEN:$PORT,pktinfo,fork EXEC:./server
