#!/bin/bash

PORT=80

while read line; do
    line=${line%%#*}; # strip comments
    read line <<< "$line"; # trim whitespace
    if [ "${line%%=*}" == "PORT" ]; then
        PORT=${line:5};
        break;
    fi
done < options

echo "Running server on port $PORT";

socat TCP4-LISTEN:$PORT,pktinfo,fork EXEC:./server
