#!/bin/bash

set -f

response="";
status_code=200;
status_msg="OK";
content_type="";

get_dir() {
}

read $method $requested_file $http_version

echo [`date`]: $SOCAT_PEERADDR accessed $requested_file >> activity.log # log requests
touch unique_ips.log
if ! grep -q "$SOCAT_PEERADDR" unique_ips.log; then
    echo $SOCAT_PEERADDR >> unique_ips.log;
fi

while read line; do
    # read headers and do something with them
    if [ -z "$line" ]; then
        break;
    fi
done


